project:
  type: website
  output-dir:docs
  resources:
    - resume.pdf

website:
  title: "Zhouxiang Sun"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

