project:
  type: website
  output-dir: docs
  resources:
    - resume.pdf

website:
  title: "Zhouxiang Sun"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.pdf
        text: Rsume

format:
  html:
    theme: yeti
    mainfont: arial
    fontcolor: "#333333"
    linkcolor: "#66ccff"
    css: styles.css
    toc: true

editor: visual

